import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/api/",
          "/dashboard",
          "/inventory",
          "/products",
          "/orders",
          "/salons",
          "/invoices",
          "/sales",
          "/customers",
          "/export",
          "/complaints",
          "/settings",
          "/notifications",
          "/audit-log",
          "/referrals",
          "/promo-codes",
          "/posts",
          "/reviews",
          "/returns",
          "/payments",
          "/registrations",
          "/samples",
          "/discounts",
          "/finance",
          "/inquiries",
          "/stylists",
          "/suppliers",
          "/salon",
          "/reservations",
          "/calendar",
          "/order-products",
          "/messages",
        ],
      },
      { userAgent: "GPTBot", allow: "/" },
      { userAgent: "Google-Extended", allow: "/" },
      { userAgent: "ChatGPT-User", allow: "/" },
      { userAgent: "Anthropic", allow: "/" },
      { userAgent: "Claude-Web", allow: "/" },
      { userAgent: "PerplexityBot", allow: "/" },
      { userAgent: "Bytespider", allow: "/" },
    ],
    sitemap: "https://www.hairland.cz/sitemap.xml",
  };
}
